### ISSUE TITLE
Optimize custom font symbols

### ISSUE THREAD

**Issue by brine** [brine/mtg-octgn#105]
The symbols used in the plugin's custom fonts really need to be optimized by someone more adept with font editor software.  I would like to see the actual symbols appear slightly larger than currently, so that they're easier to read in deck editor and proxy generator.  Also, the kerning and positioning of each symbol should be verified.

**Comment by ccbrown** [comment]
I may look at this more later, but here are my initial thoughts:

There's at least one change that should happen: The original glyphs were placed in codepoints normally used for other characters such as "Ą". On the off-chance that someone in the world actually wants to type these characters in chat, they won't be able to (they'll get an MTG symbol instead). These glyphs should be moved into one of Unicode's private use areas, so they don't shadow any other characters. I've put the things I've added in one of these areas, but left the originals where they were for the time being.

As for the sizing, the symbols appear to be pretty accurate compared to a modern card:

![name](https://cloud.githubusercontent.com/assets/1731074/12104546/7a5f62b4-b301-11e5-979c-3f3f3761a520.png)

They rest very slightly below the baseline and extend very slightly above the font's ascent. And the preview images for Oath actually have all of the glyphs smaller than this.

The proxies would look far better if OCTGN didn't render them in what's probably just about the worst possible way. The text will always be a little blurry at most sizes until they rewrite the generator. Also, if they rewrite it... color font support would be relatively easy to add there. In fact, it wouldn't be too hard to add without rewriting it, but it would involve adding a new library to the project to read the font's color palette and layers. Maybe someone should open an issue over there for this.

But in the meantime, there are a few things I think could be done to improve the look of the proxy cards.

The size of the name / cost text is actually a little too small right now:

![image](https://cloud.githubusercontent.com/assets/1731074/12106600/0deafe62-b316-11e5-92ec-8c16f19295e4.png)
![before](https://cloud.githubusercontent.com/assets/1731074/12106601/10cdd49c-b316-11e5-8066-50128ae29313.png)

So you can just bump that up. Adding a heavier mplantin font for that and the card type would make the proxies match the real thing a little closer too:

![after](https://cloud.githubusercontent.com/assets/1731074/12106619/3411290e-b316-11e5-89cf-e01bbab2d266.png)

So blurry...

At small font sizes, using drop shadows tends to look better than outlines:

![outline](https://cloud.githubusercontent.com/assets/1731074/12106645/6c0f142e-b316-11e5-9f06-095959eff3d7.png)
![shadow](https://cloud.githubusercontent.com/assets/1731074/12106648/728f1560-b316-11e5-8198-a9e54283c6c0.png)

Can also use an emdash (—) instead of the double hyphen.

For the table, I find it nearly unusable as-is. What I recommend is actually to *not* use the mplantin font. Instead I use a font with only the symbols, so the other characters fall back to the default:

![table](https://cloud.githubusercontent.com/assets/1731074/12106798/0391da06-b318-11e5-9932-fa574fc53325.png)

That's also slightly larger (14 instead of 12).

**Comment by ccbrown** [comment]
In fact, I'm actually of the opinion that the mplantin font should *only* be used for the proxy generation (and not chat). Even Wizards hardly uses it anywhere else. If you'd like, I can upload that font file for you too.

**Comment by brine** [comment]
well as it is now, the hybrid symbols are actually larger than the regular ones so at the very least we should have a level of consistency there.  My main concern when I (hastily) edited the font for symbols was visibility, I wanted to make sure that users could easily see and recognize the symbols (mainly because I didn't have access to text coloring as a visual cue) so I'm not against making them bigger than normal.

I agree with moving the symbols to unused glyph slots - especially since we have the ligatures now to make user-searching and typing the symbols less painful.

As for the proxy stuff, AFAIK it was a compromise between generator efficiency and working around the platform's oddities.  I don't know what areas could be rewritten or improved upon, but the proxy gen is Gravecorp's realm so he would be the one to talk to about it.

**Comment by brine** [comment]
and yeah I don't really have any attachment to the font being used outside the proxy templates.  It was mostly a "hey look, they added custom font support, might as well use it" sort of thing.  At the time I really liked the font and thought it was very easy on the eyes to read, but I'm not opposed to dropping down to a more basic font for the deck editor, game chat and context menus

**Comment by ccbrown** [comment]
The hybrid symbols are actually larger than the others on cards:

![vassal soul](http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=253521&type=card)

**Comment by brine** [comment]
huh never would have guessed.

**Comment by brine** [comment]
btw, if you ever need a quick message or contact I'm usually around the octgn chatroom (irc.freenode.net #octgn) and all the octgn devs are there too

**Comment by brine** [comment]
ok so the current plan here is to move all mtg-related symbols to an unused section of the font, then have an mplantin version and a regular-text version.  The existing sizing and kerning is fine as-is.

If you wanted to make these changes to the font, that'd be a big appreciation as I'm not confident in my font-editing skills :) .  Then I can handle all the card data for the new symbol syntax for when the next set rolls out.

I'm currently looking into getting the color glyphs set up for OCTGN, and am working with the dev team to figure out a solution.

**Comment by ccbrown** [comment]
I'm unlikely to have time to make those changes before Oath. Things got really busy since the holiday season ended. :-/

The regular text version I attached to my comment above should be good to go though if you want to use that.

**Comment by brine** [comment]
No worries I'll get it up and running

**Comment by brine** [comment]
new OCTGN updates allow for actual symbol images in the text blocks, which should properly address this.  There are plans to extend the symbols to chat and dialog windows as well.
